name: droidcon_app
description: Flutter app for Kenya's 3rd Android Developer Conference - droidcon
  to be held in Nairobi from November 16-18th 2022.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.6
  dio: ^5.5.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  drawable: ^0.1.0
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_performance: ^0.10.0+2
  firebase_performance_dio: ^0.7.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.2.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^1.0.3+1
  flutter_svg: ^2.0.10+1
  form_builder_cupertino_fields: ^0.2.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.2
  get_time_ago: ^1.3.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  hydrated_riverpod: ^0.0.3
  intl: ^0.18.1
  json_serializable: ^6.8.0
  package_info: ^2.0.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  pretty_dio_logger: ^1.3.1
  sizer: ^2.0.15
  social_share: ^2.3.1
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mockito: ^5.4.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash-dark.png
  android_gravity: bottom
  ios_content_mode: bottom
  android_12:
    image: assets/splash/splash.png
    image_dark: assets/splash/splash-dark.png
    color: "#FFFFFF"
    color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - environments/
    - assets/images/
    - assets/svgs/
    - assets/google_fonts/
    - assets/afrikons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
